<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class LocationsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $locations = [
            ['id' => 1, 'state' => 'California', 'city' => 'California Average'],
            ['id' => 2, 'state' => 'California', 'city' => 'Alameda County'],
            ['id' => 3, 'state' => 'California', 'city' => 'Amador County'],
            ['id' => 4, 'state' => 'California', 'city' => 'Calaveras County'],
            ['id' => 5, 'state' => 'California', 'city' => 'Colusa County'],
            ['id' => 6, 'state' => 'California', 'city' => 'Contra Costa County'],
            ['id' => 7, 'state' => 'California', 'city' => 'Del Norte County'],
            ['id' => 8, 'state' => 'California', 'city' => 'El Dorado County'],
            ['id' => 9, 'state' => 'California', 'city' => 'Fresno County'],
            ['id' => 10, 'state' => 'California', 'city' => 'Glenn County'],
            ['id' => 11, 'state' => 'California', 'city' => 'Humboldt County'],
            ['id' => 12, 'state' => 'California', 'city' => 'Imperial County'],
            ['id' => 13, 'state' => 'California', 'city' => 'Inyo County'],
            ['id' => 14, 'state' => 'California', 'city' => 'Kern County'],
            ['id' => 15, 'state' => 'California', 'city' => 'Kings County'],
            ['id' => 16, 'state' => 'California', 'city' => 'Lake County'],
            ['id' => 17, 'state' => 'California', 'city' => 'Lassen County'],
            ['id' => 18, 'state' => 'California', 'city' => 'Los Angeles County'],
            ['id' => 19, 'state' => 'California', 'city' => 'Madera County'],
            ['id' => 20, 'state' => 'California', 'city' => 'Marin County'],
            ['id' => 21, 'state' => 'California', 'city' => 'Mariposa County'],
            ['id' => 22, 'state' => 'California', 'city' => 'Mendocino County'],
            ['id' => 23, 'state' => 'California', 'city' => 'Merced County'],
            ['id' => 24, 'state' => 'California', 'city' => 'Modoc County'],
            ['id' => 25, 'state' => 'California', 'city' => 'Mono County'],
            ['id' => 26, 'state' => 'California', 'city' => 'Monterey County'],
            ['id' => 27, 'state' => 'California', 'city' => 'Napa County'],
            ['id' => 28, 'state' => 'California', 'city' => 'Nevada County'],
            ['id' => 29, 'state' => 'California', 'city' => 'Orange County'],
            ['id' => 30, 'state' => 'California', 'city' => 'Placer County'],
            ['id' => 31, 'state' => 'California', 'city' => 'Plumas County'],
            ['id' => 32, 'state' => 'California', 'city' => 'Riverside County'],
            ['id' => 33, 'state' => 'California', 'city' => 'Sacramento County'],
            ['id' => 34, 'state' => 'California', 'city' => 'San Benito County'],
            ['id' => 35, 'state' => 'California', 'city' => 'San Bernadino County'],
            ['id' => 36, 'state' => 'California', 'city' => 'San Diego County'],
            ['id' => 37, 'state' => 'California', 'city' => 'San Francisco County'],
            ['id' => 38, 'state' => 'California', 'city' => 'San Joaquin County'],
            ['id' => 39, 'state' => 'California', 'city' => 'San Luis Obispo County'],
            ['id' => 40, 'state' => 'California', 'city' => 'San Mateo County'],
            ['id' => 41, 'state' => 'California', 'city' => 'Santa Barbara County'],
            ['id' => 42, 'state' => 'California', 'city' => 'Santa Clara County'],
            ['id' => 43, 'state' => 'California', 'city' => 'Santa Cruz County'],
            ['id' => 44, 'state' => 'California', 'city' => 'Shasta County'],
            ['id' => 45, 'state' => 'California', 'city' => 'Sierra County'],
            ['id' => 46, 'state' => 'California', 'city' => 'Siskiyou County'],
            ['id' => 47, 'state' => 'California', 'city' => 'Solano County'],
            ['id' => 48, 'state' => 'California', 'city' => 'Sonoma County'],
            ['id' => 49, 'state' => 'California', 'city' => 'Stanislaus County'],
            ['id' => 50, 'state' => 'California', 'city' => 'Sutter County'],
            ['id' => 51, 'state' => 'California', 'city' => 'Tehama County'],
            ['id' => 52, 'state' => 'California', 'city' => 'Trinity County'],
            ['id' => 53, 'state' => 'California', 'city' => 'Tulare County'],
            ['id' => 54, 'state' => 'California', 'city' => 'Tuolumne County'],
            ['id' => 55, 'state' => 'California', 'city' => 'Ventura County'],
            ['id' => 56, 'state' => 'California', 'city' => 'Yolo County'],
            ['id' => 57, 'state' => 'California', 'city' => 'Yuba County'],
            ['id' => 58, 'state' => 'Alabama', 'city' => 'BIRMINGHAM'],
            ['id' => 59, 'state' => 'Alabama', 'city' => 'HUNTSVILLE'],
            ['id' => 60, 'state' => 'Alabama', 'city' => 'MOBILE'],
            ['id' => 61, 'state' => 'Alabama', 'city' => 'MONTGOMERY'],
            ['id' => 62, 'state' => 'Alaska', 'city' => 'ANCHORAGE'],
            ['id' => 63, 'state' => 'Alaska', 'city' => 'ANNETTE'],
            ['id' => 64, 'state' => 'Alaska', 'city' => 'BARROW'],
            ['id' => 65, 'state' => 'Alaska', 'city' => 'BETHEL'],
            ['id' => 66, 'state' => 'Alaska', 'city' => 'BETTLES'],
            ['id' => 67, 'state' => 'Alaska', 'city' => 'BIG DELTA'],
            ['id' => 68, 'state' => 'Alaska', 'city' => 'COLD BAY'],
            ['id' => 69, 'state' => 'Alaska', 'city' => 'FAIRBANKS'],
            ['id' => 70, 'state' => 'Alaska', 'city' => 'GULKANA'],
            ['id' => 71, 'state' => 'Alaska', 'city' => 'HOMER'],
            ['id' => 72, 'state' => 'Alaska', 'city' => 'JUNEAU'],
            ['id' => 73, 'state' => 'Alaska', 'city' => 'KING SALMON'],
            ['id' => 74, 'state' => 'Alaska', 'city' => 'KODIAK'],
            ['id' => 75, 'state' => 'Alaska', 'city' => 'KOTZEBUE'],
            ['id' => 76, 'state' => 'Alaska', 'city' => 'MCGRATH'],
            ['id' => 77, 'state' => 'Alaska', 'city' => 'NOME'],
            ['id' => 78, 'state' => 'Alaska', 'city' => 'ST. PAUL ISLAND'],
            ['id' => 79, 'state' => 'Alaska', 'city' => 'TALKEETNA'],
            ['id' => 80, 'state' => 'Alaska', 'city' => 'UNALAKLEET'],
            ['id' => 81, 'state' => 'Alaska', 'city' => 'VALDEZ'],
            ['id' => 82, 'state' => 'Alaska', 'city' => 'YAKUTAT'],
            ['id' => 83, 'state' => 'Arizona', 'city' => 'FLAGSTAFF'],
            ['id' => 84, 'state' => 'Arizona', 'city' => 'PHOENIX'],
            ['id' => 85, 'state' => 'Arizona', 'city' => 'TUCSON'],
            ['id' => 86, 'state' => 'Arizona', 'city' => 'WINSLOW'],
            ['id' => 87, 'state' => 'Arizona', 'city' => 'YUMA'],
            ['id' => 88, 'state' => 'Arkansas', 'city' => 'FORT SMITH'],
            ['id' => 89, 'state' => 'Arkansas', 'city' => 'LITTLE ROCK'],
            ['id' => 90, 'state' => 'Arkansas', 'city' => 'NORTH LITTLE ROCK'],
            ['id' => 91, 'state' => 'Colorado', 'city' => 'ALAMOSA'],
            ['id' => 92, 'state' => 'Colorado', 'city' => 'COLORADO SPRINGS'],
            ['id' => 93, 'state' => 'Colorado', 'city' => 'DENVER'],
            ['id' => 94, 'state' => 'Colorado', 'city' => 'GRAND JUNCTION'],
            ['id' => 95, 'state' => 'Colorado', 'city' => 'PUEBLO'],
            ['id' => 96, 'state' => 'Connecticut', 'city' => 'BRIDGEPORT'],
            ['id' => 97, 'state' => 'Connecticut', 'city' => 'HARTFORD'],
            ['id' => 98, 'state' => 'Delaware', 'city' => 'WILMINGTON'],
            ['id' => 99, 'state' => 'Disctrict of Columbia', 'city' => 'WASHINGTON'],
            ['id' => 100, 'state' => 'Florida', 'city' => 'APALACHICOLA'],
            ['id' => 101, 'state' => 'Florida', 'city' => 'DAYTONA BEACH'],
            ['id' => 102, 'state' => 'Florida', 'city' => 'FORT MYERS'],
            ['id' => 103, 'state' => 'Florida', 'city' => 'GAINESVILLE'],
            ['id' => 104, 'state' => 'Florida', 'city' => 'JACKSONVILLE'],
            ['id' => 105, 'state' => 'Florida', 'city' => 'KEY WEST'],
            ['id' => 106, 'state' => 'Florida', 'city' => 'MIAMI'],
            ['id' => 107, 'state' => 'Florida', 'city' => 'ORLANDO'],
            ['id' => 108, 'state' => 'Florida', 'city' => 'PENSACOLA'],
            ['id' => 109, 'state' => 'Florida', 'city' => 'TALLAHASSEE'],
            ['id' => 110, 'state' => 'Florida', 'city' => 'TAMPA'],
            ['id' => 111, 'state' => 'Florida', 'city' => 'VERO BEACH'],
            ['id' => 112, 'state' => 'Florida', 'city' => 'WEST PALM BEACH'],
            ['id' => 113, 'state' => 'Georgia', 'city' => 'ATHENS'],
            ['id' => 114, 'state' => 'Georgia', 'city' => 'ATLANTA'],
            ['id' => 115, 'state' => 'Georgia', 'city' => 'AUGUSTA'],
            ['id' => 116, 'state' => 'Georgia', 'city' => 'COLUMBUS'],
            ['id' => 117, 'state' => 'Georgia', 'city' => 'MACON'],
            ['id' => 118, 'state' => 'Georgia', 'city' => 'SAVANNAH'],
            ['id' => 119, 'state' => 'Hawaii', 'city' => 'HILO'],
            ['id' => 120, 'state' => 'Hawaii', 'city' => 'HONOLULU'],
            ['id' => 121, 'state' => 'Hawaii', 'city' => 'KAHULUI'],
            ['id' => 122, 'state' => 'Hawaii', 'city' => 'LIHUE'],
            ['id' => 123, 'state' => 'Idaho', 'city' => 'BOISE'],
            ['id' => 124, 'state' => 'Idaho', 'city' => 'LEWISTON'],
            ['id' => 125, 'state' => 'Idaho', 'city' => 'POCATELLO'],
            ['id' => 126, 'state' => 'Illinis', 'city' => 'CHICAGO'],
            ['id' => 127, 'state' => 'Illinis', 'city' => 'MOLINE'],
            ['id' => 128, 'state' => 'Illinis', 'city' => 'PEORIA'],
            ['id' => 129, 'state' => 'Illinis', 'city' => 'ROCKFORD'],
            ['id' => 130, 'state' => 'Illinis', 'city' => 'SPRINGFIELD'],
            ['id' => 131, 'state' => 'Indiana', 'city' => 'EVANSVILLE'],
            ['id' => 132, 'state' => 'Indiana', 'city' => 'FORT WAYNE'],
            ['id' => 133, 'state' => 'Indiana', 'city' => 'INDIANAPOLIS'],
            ['id' => 134, 'state' => 'Indiana', 'city' => 'SOUTH BEND'],
            ['id' => 135, 'state' => 'Iowa', 'city' => 'DES MOINES'],
            ['id' => 136, 'state' => 'Iowa', 'city' => 'DUBUQUE'],
            ['id' => 137, 'state' => 'Iowa', 'city' => 'SIOUX CITY'],
            ['id' => 138, 'state' => 'Iowa', 'city' => 'WATERLOO'],
            ['id' => 139, 'state' => 'Kansas', 'city' => 'CONCORDIA'],
            ['id' => 140, 'state' => 'Kansas', 'city' => 'DODGE CITY'],
            ['id' => 141, 'state' => 'Kansas', 'city' => 'GOODLAND'],
            ['id' => 142, 'state' => 'Kansas', 'city' => 'TOPEKA'],
            ['id' => 143, 'state' => 'Kansas', 'city' => 'WICHITA'],
            ['id' => 144, 'state' => 'Ohio', 'city' => 'GREATER CINCINNATI'],
            ['id' => 145, 'state' => 'Kentucky', 'city' => 'JACKSON'],
            ['id' => 146, 'state' => 'Kentucky', 'city' => 'LEXINGTON'],
            ['id' => 147, 'state' => 'Kentucky', 'city' => 'LOUISVILLE'],
            ['id' => 148, 'state' => 'Kentucky', 'city' => 'PADUCAH'],
            ['id' => 149, 'state' => 'Louisiana', 'city' => 'BATON ROUGE'],
            ['id' => 150, 'state' => 'Louisiana', 'city' => 'LAKE CHARLES'],
            ['id' => 151, 'state' => 'Louisiana', 'city' => 'NEW ORLEANS'],
            ['id' => 152, 'state' => 'Louisiana', 'city' => 'SHREVEPORT'],
            ['id' => 153, 'state' => 'Maine', 'city' => 'CARIBOU'],
            ['id' => 154, 'state' => 'Maine', 'city' => 'PORTLAND'],
            ['id' => 155, 'state' => 'Maryland', 'city' => 'BALTIMORE'],
            ['id' => 156, 'state' => 'Massachusetts', 'city' => 'BLUE HILL'],
            ['id' => 157, 'state' => 'Massachusetts', 'city' => 'BOSTON'],
            ['id' => 158, 'state' => 'Massachusetts', 'city' => 'WORCESTER'],
            ['id' => 159, 'state' => 'Michigan', 'city' => 'ALPENA'],
            ['id' => 160, 'state' => 'Michigan', 'city' => 'DETROIT'],
            ['id' => 161, 'state' => 'Michigan', 'city' => 'FLINT'],
            ['id' => 162, 'state' => 'Michigan', 'city' => 'GRAND RAPIDS'],
            ['id' => 163, 'state' => 'Michigan', 'city' => 'HOUGHTON LAKE'],
            ['id' => 164, 'state' => 'Michigan', 'city' => 'LANSING'],
            ['id' => 165, 'state' => 'Michigan', 'city' => 'MARQUETTE'],
            ['id' => 166, 'state' => 'Michigan', 'city' => 'MUSKEGON'],
            ['id' => 167, 'state' => 'Michigan', 'city' => 'SAULT STE. MARIE'],
            ['id' => 168, 'state' => 'Minnesota', 'city' => 'DULUTH'],
            ['id' => 169, 'state' => 'Minnesota', 'city' => 'NTERNATIONAL FALLS'],
            ['id' => 170, 'state' => 'Minnesota', 'city' => 'INNEAPOLIS-ST.PAUL'],
            ['id' => 171, 'state' => 'Minnesota', 'city' => 'ROCHESTER'],
            ['id' => 172, 'state' => 'Minnesota', 'city' => 'SAINT CLOUD'],
            ['id' => 173, 'state' => 'Mississippi', 'city' => 'JACKSON'],
            ['id' => 174, 'state' => 'Mississippi', 'city' => 'MERIDIAN'],
            ['id' => 175, 'state' => 'Mississippi', 'city' => 'TUPELO'],
            ['id' => 176, 'state' => 'Missouri', 'city' => 'COLUMBIA'],
            ['id' => 177, 'state' => 'Missouri', 'city' => 'KANSAS CITY'],
            ['id' => 178, 'state' => 'Missouri', 'city' => 'ST. LOUIS'],
            ['id' => 179, 'state' => 'Missouri', 'city' => 'SPRINGFIELD'],
            ['id' => 180, 'state' => 'Montana', 'city' => 'BILLINGS'],
            ['id' => 181, 'state' => 'Montana', 'city' => 'GLASGOW'],
            ['id' => 182, 'state' => 'Montana', 'city' => 'GREAT FALLS'],
            ['id' => 183, 'state' => 'Montana', 'city' => 'HAVRE'],
            ['id' => 184, 'state' => 'Montana', 'city' => 'HELENA'],
            ['id' => 185, 'state' => 'Montana', 'city' => 'KALISPELL'],
            ['id' => 186, 'state' => 'Montana', 'city' => 'MISSOULA'],
            ['id' => 187, 'state' => 'Nebraska', 'city' => 'GRAND ISLAND'],
            ['id' => 188, 'state' => 'Nebraska', 'city' => 'LINCOLN'],
            ['id' => 189, 'state' => 'Nebraska', 'city' => 'NORFOLK'],
            ['id' => 190, 'state' => 'Nebraska', 'city' => 'NORTH PLATTE'],
            ['id' => 191, 'state' => 'Nebraska', 'city' => 'OMAHA '],
            ['id' => 192, 'state' => 'Nebraska', 'city' => 'SCOTTSBLUFF'],
            ['id' => 193, 'state' => 'Nebraska', 'city' => 'VALENTINE'],
            ['id' => 194, 'state' => 'Nevada', 'city' => 'ELKO'],
            ['id' => 195, 'state' => 'Nevada', 'city' => 'ELY'],
            ['id' => 196, 'state' => 'Nevada', 'city' => 'LAS VEGAS'],
            ['id' => 197, 'state' => 'Nevada', 'city' => 'RENO'],
            ['id' => 198, 'state' => 'Nevada', 'city' => 'WINNEMUCCA'],
            ['id' => 199, 'state' => 'New Hampshire', 'city' => 'CONCORD'],
            ['id' => 200, 'state' => 'New Hampshire', 'city' => 'MT. WASHINGTON'],
            ['id' => 201, 'state' => 'New Jersey', 'city' => 'ATLANTIC CITY'],
            ['id' => 202, 'state' => 'New Jersey', 'city' => 'NEWARK'],
            ['id' => 203, 'state' => 'New Mexico', 'city' => 'ALBUQUERQUE'],
            ['id' => 204, 'state' => 'New Mexico', 'city' => 'CLAYTON'],
            ['id' => 205, 'state' => 'New Mexico', 'city' => 'ROSWELL'],
            ['id' => 206, 'state' => 'New York', 'city' => 'ALBANY'],
            ['id' => 207, 'state' => 'New York', 'city' => 'BINGHAMTON'],
            ['id' => 208, 'state' => 'New York', 'city' => 'BUFFALO'],
            ['id' => 209, 'state' => 'New York', 'city' => 'ISLIP'],
            ['id' => 210, 'state' => 'New York', 'city' => 'NEW YORK '],
            ['id' => 211, 'state' => 'New York', 'city' => 'ROCHESTER'],
            ['id' => 212, 'state' => 'New York', 'city' => 'SYRACUSE'],
            ['id' => 213, 'state' => 'North Carolina', 'city' => 'ASHEVILLE'],
            ['id' => 214, 'state' => 'North Carolina', 'city' => 'CAPE HATTERAS'],
            ['id' => 215, 'state' => 'North Carolina', 'city' => 'CHARLOTTE'],
            ['id' => 216, 'state' => 'North Carolina', 'city' => ' GREENSBORO'],
            ['id' => 217, 'state' => 'North Carolina', 'city' => 'RALEIGH'],
            ['id' => 218, 'state' => 'North Carolina', 'city' => 'WILMINGTON'],
            ['id' => 219, 'state' => 'North Dakota', 'city' => 'BISMARCK'],
            ['id' => 220, 'state' => 'North Dakota', 'city' => 'FARGO'],
            ['id' => 221, 'state' => 'North Dakota', 'city' => 'GRAND FORKS'],
            ['id' => 222, 'state' => 'North Dakota', 'city' => 'WILLISTON'],
            ['id' => 223, 'state' => 'Ohio', 'city' => 'AKRON'],
            ['id' => 224, 'state' => 'Ohio', 'city' => 'CLEVELAND'],
            ['id' => 225, 'state' => 'Ohio', 'city' => 'COLUMBUS'],
            ['id' => 226, 'state' => 'Ohio', 'city' => 'DAYTON'],
            ['id' => 227, 'state' => 'Ohio', 'city' => 'MANSFIELD'],
            ['id' => 228, 'state' => 'Ohio', 'city' => 'TOLEDO'],
            ['id' => 229, 'state' => 'Ohio', 'city' => 'YOUNGSTOWN'],
            ['id' => 230, 'state' => 'Oklahoma', 'city' => 'OKLAHOMA CITY'],
            ['id' => 231, 'state' => 'Oklahoma', 'city' => 'TULSA'],
            ['id' => 232, 'state' => 'Oregon', 'city' => 'ASTORIA'],
            ['id' => 233, 'state' => 'Oregon', 'city' => 'BURNS'],
            ['id' => 234, 'state' => 'Oregon', 'city' => 'EUGENE'],
            ['id' => 235, 'state' => 'Oregon', 'city' => 'MEDFORD'],
            ['id' => 236, 'state' => 'Oregon', 'city' => 'PENDLETON'],
            ['id' => 237, 'state' => 'Oregon', 'city' => 'PORTLAND'],
            ['id' => 238, 'state' => 'Oregon', 'city' => 'SALEM'],
            ['id' => 239, 'state' => 'Oregon', 'city' => 'SEXTON SUMMIT'],
            ['id' => 240, 'state' => 'Pennsylvania', 'city' => 'ALLENTOWN'],
            ['id' => 241, 'state' => 'Pennsylvania', 'city' => 'ERIE'],
            ['id' => 242, 'state' => 'Pennsylvania', 'city' => 'HARRISBURG'],
            ['id' => 243, 'state' => 'Pennsylvania', 'city' => 'PHILADELPHIA'],
            ['id' => 244, 'state' => 'Pennsylvania', 'city' => 'PITTSBURGH'],
            ['id' => 245, 'state' => 'Pennsylvania', 'city' => 'AVOCA'],
            ['id' => 246, 'state' => 'Pennsylvania', 'city' => 'WILLIAMSPORT'],
            ['id' => 247, 'state' => 'Rhode Island', 'city' => 'PROVIDENCE'],
            ['id' => 248, 'state' => 'South Carolina', 'city' => 'CHARLESTON '],
            ['id' => 249, 'state' => 'South Carolina', 'city' => 'COLUMBIA'],
            ['id' => 250, 'state' => 'South Carolina', 'city' => 'GREENVILLE'],
            ['id' => 251, 'state' => 'South Dakota', 'city' => 'ABERDEEN'],
            ['id' => 252, 'state' => 'South Dakota', 'city' => 'HURON'],
            ['id' => 253, 'state' => 'South Dakota', 'city' => 'RAPID CITY'],
            ['id' => 254, 'state' => 'South Dakota', 'city' => 'SIOUX FALLS'],
            ['id' => 255, 'state' => 'Tennessee', 'city' => ' BRISTOL'],
            ['id' => 256, 'state' => 'Tennessee', 'city' => 'CHATTANOOGA'],
            ['id' => 257, 'state' => 'Tennessee', 'city' => 'KNOXVILLE'],
            ['id' => 258, 'state' => 'Tennessee', 'city' => 'MEMPHIS'],
            ['id' => 259, 'state' => 'Tennessee', 'city' => 'NASHVILLE'],
            ['id' => 260, 'state' => 'Tennessee', 'city' => 'OAK RIDGE'],
            ['id' => 261, 'state' => 'Texas', 'city' => 'ABILENE'],
            ['id' => 262, 'state' => 'Texas', 'city' => 'AMARILLO'],
            ['id' => 263, 'state' => 'Texas', 'city' => 'AUSTIN'],
            ['id' => 264, 'state' => 'Texas', 'city' => 'BROWNSVILLE'],
            ['id' => 265, 'state' => 'Texas', 'city' => 'CORPUS CHRISTI'],
            ['id' => 266, 'state' => 'Texas', 'city' => 'DALLAS-FORT WORTH'],
            ['id' => 267, 'state' => 'Texas', 'city' => 'DALLAS-LOVE FIELD'],
            ['id' => 268, 'state' => 'Texas', 'city' => 'DEL RIO'],
            ['id' => 269, 'state' => 'Texas', 'city' => 'EL PASO'],
            ['id' => 270, 'state' => 'Texas', 'city' => 'GALVESTON'],
            ['id' => 271, 'state' => 'Texas', 'city' => 'HOUSTON'],
            ['id' => 272, 'state' => 'Texas', 'city' => 'LUBBOCK'],
            ['id' => 273, 'state' => 'Texas', 'city' => 'MIDLAND-ODESSA'],
            ['id' => 274, 'state' => 'Texas', 'city' => 'PORT ARTHUR'],
            ['id' => 275, 'state' => 'Texas', 'city' => 'SAN ANGELO'],
            ['id' => 276, 'state' => 'Texas', 'city' => 'SAN ANTONIO'],
            ['id' => 277, 'state' => 'Texas', 'city' => 'VICTORIA'],
            ['id' => 278, 'state' => 'Texas', 'city' => 'WACO'],
            ['id' => 279, 'state' => 'Texas', 'city' => 'WICHITA FALLS'],
            ['id' => 280, 'state' => 'Utah', 'city' => 'MILFORD'],
            ['id' => 281, 'state' => 'Utah', 'city' => 'SALT LAKE CITY'],
            ['id' => 282, 'state' => 'Vermont', 'city' => 'BURLINGTON'],
            ['id' => 283, 'state' => 'Virginia', 'city' => 'LYNCHBURG'],
            ['id' => 284, 'state' => 'Virginia', 'city' => 'NORFOLK'],
            ['id' => 285, 'state' => 'Virginia', 'city' => 'RICHMOND'],
            ['id' => 286, 'state' => 'Virginia', 'city' => 'ROANOKE'],
            ['id' => 287, 'state' => 'Washington', 'city' => 'OLYMPIA'],
            ['id' => 288, 'state' => 'Washington', 'city' => 'QUILLAYUTE'],
            ['id' => 289, 'state' => 'Washington', 'city' => 'SEATTLE'],
            ['id' => 290, 'state' => 'Washington', 'city' => 'SPOKANE'],
            ['id' => 291, 'state' => 'Washington', 'city' => 'WALLA WALLA'],
            ['id' => 292, 'state' => 'Washington', 'city' => 'YAKIMA'],
            ['id' => 293, 'state' => 'West Virginia', 'city' => 'BECKLEY'],
            ['id' => 294, 'state' => 'West Virginia', 'city' => 'CHARLESTON'],
            ['id' => 295, 'state' => 'West Virginia', 'city' => 'ELKINS'],
            ['id' => 296, 'state' => 'West Virginia', 'city' => 'HUNTINGTON'],
            ['id' => 297, 'state' => 'Wisconsin', 'city' => 'GREEN BAY'],
            ['id' => 298, 'state' => 'Wisconsin', 'city' => 'LA CROSSE'],
            ['id' => 299, 'state' => 'Wisconsin', 'city' => 'MADISON'],
            ['id' => 300, 'state' => 'Wisconsin', 'city' => 'MILWAUKEE'],
            ['id' => 301, 'state' => 'Wyoming', 'city' => 'CASPER'],
            ['id' => 302, 'state' => 'Wyoming', 'city' => 'CHEYENNE'],
            ['id' => 303, 'state' => 'Wyoming', 'city' => 'LANDER'],
            ['id' => 304, 'state' => 'Wyoming', 'city' => 'SHERIDAN']
        ];

        \DB::table('locations')->insert($locations);
    }
}
