@extends('layouts.app')

@push('meta-tags')

    <title>Green Places | Erase Your Company Footprint</title>
    <meta name="description" content="We believe being a green workplace is an ROI Positive decision for small businesses, but many don’t do it because of the false perception that it’s hard, complicated, and unprofitable.">
    <meta name="keywords" content="{{ env('APP_NAME') }}, Terms">

    <meta property="og:url"          content="{{ Request::url() }}" />
    <meta property="og:title"        content="Green Places | Erase Your Company Footprint" />
    <meta property="og:description"  content="We believe being a green workplace is an ROI Positive decision for small businesses, but many don’t do it because of the false perception that it’s hard, complicated, and unprofitable." />
    <meta property="og:image"        content="{{ asset('images/green_places_logo_png.png') }}" />
    <meta property="og:image:type"   content="image/png">
   
@endpush

@section('content')
    <div class="greenplaces-main">
        <section class="greenplaces-terms-page">
            <div class="container">
                <div class="greenplaces-terms-wrapper">
                    <h3 class="greenp-subtitle-small">PRIVACY POLICY</h3>
                    <p class="greenp-paragraph-text">Effective date: June 28, 2021</p>
                    <p class="greenp-paragraph-text">This Privacy Policy (the “Policy”) explains how Green Places, Inc. (“us,” “our,” or “we”) collects, uses, discloses, and protects personal information that we collect from you through the website <a href="www.greenplacestowork.com">www.greenplacestowork.com</a> (the “Website”). </p>
                    <div class="">
                        <h5>Information We Collect</h5>
                        <h6>You may provide us with information about you when you use or access the Website. This information may include the following:</h6>
                        <ul>
                            <li>Contact information, such as name, email address, and phone number.</li>
                            <li>Information about your business to help us provide our services, such as to calculate your carbon footprint, describe your sustainability strategies, and promote your business. This information might include your location, square footage, number of employees, and your use of cloud hosted servers. We may also collect contact information for your identified business representative, if applicable, such as name, phone number, or email address.</li>
                            <li>Professional and employment-related information, such as your resume, cover letter, and any other information you choose to provide in your employment inquiries or applications.</li>
                            <li>Other: Any other information you choose to provide when you contact us or otherwise engage with us through the Websites, such as when you request information or engage in our chat features.</li>
                        </ul>
                        <h5>Information we collect automatically</h5>
                        <h6>We also may collect certain other information automatically when you visit the Website, such as the following:</h6>
                        <ul>
                            <li>Browser and Device Information: Certain information is automatically collected by most websites, such as information about your device and your browser. For example, we may receive device identifiers such as IP address and MAC address, operating system type and version, and Internet browser type and version. </li>
                            <li>Search Engine and Other Referrals: When a third party refers you to our Website, such as clicking on a link to our page from a Google search, or clicking on an online ad for our services, we will receive some information about your device and your interaction with the referring site or content. </li>
                            <li>Activity Reporting and Log Data: We may receive log information related to your activities while using the Website, such as text queries. In addition, Google Analytics uses cookies to help us analyze how visitors use the Website. The information generated by the cookies about your use of the Website includes your IP address. If you so choose, you may be able to opt out by turning off cookies in the preferences settings in your browser. For more information on Google Analytics, including how Google Analytics collects, uses, and discloses information, refer to the following page: <a href="https://policies.google.com/technologies/partner-sites">https://policies.google.com/technologies/partner-sites</a>.</li>
                            <li>Location Information: We may receive your approximate location or data that indicates your approximate location, such as your IP address.</li>
                            <li>Email Analytics: To help us gauge the effectiveness of our communications, we use common digital tools that allow us to see if you opened an email we sent or visited a link in those emails.</li>
                        </ul>
                        <h5>How We Use Personal Information</h5>
                        <h6>We may use personal information that we collect about you for purposes that include the following:</h6>
                        <ul>
                            <li>Providing the Website and supporting the features available to you.</li>
                            <li>Personalizing your digital experience with us, such as enhancing features and designing relevant alerts, products, or services.</li>
                            <li>Understanding how you and our clients use our Website and to determine what features and services may interest you and our clients. </li>
                            <li>Operating and improving our organization and our services.</li>
                            <li>To communicate with you and others, including responding to requests and providing promotional content.</li>
                            <li>For our recruitment and hiring purposes, including evaluating and processing your employment application.</li>
                            <li>Troubleshooting, de-bugging, and otherwise addressing issues that may arise with the functionality of the Website. </li>
                            <li>Protecting the legal rights, property, safety, and security of records or information, our customers and Website users, our organization and others, including detecting and preventing fraud, misuse of the Website, and other unauthorized activity.</li>
                            <li>Complying with industry standards, applicable law, judicial process, any properly authorized civil, criminal, or regulatory investigation, or any subpoena or summons issued by a competent authority.</li>
                            <li>Enforcing our policies, terms of use, or rights arising from contracts.</li>
                            <li>For such purposes as you may authorize at the time you submit the information.</li>
                        </ul>
                        <h6>We also may aggregate or de-identify personal information by removing any details that identify you personally. Aggregated or de-identified information will not be subject to this Policy and will be used to the extent permissible under applicable law.</h6>
                        <h5>With Whom We Share Your Information</h5>
                        <h6>We may disclose personal information:</h6>
                        <ul>
                            <li>To our affiliates, business partners, or channel partners.</li>
                            <li>To our contractors, service providers, and other third parties we use to support our organization and the Website, including for marketing purposes. </li>
                            <li>To government agencies or others as necessary to comply with any court order, law, or legal process, including to respond to any government or regulatory request, and consistent with other purposes authorized by law.</li>
                            <li>To other organizations, such as a buyer or other successor in interest, in the event of an actual or potential merger, divestiture, restructuring, reorganization, dissolution, or other sale, exchange, or transfer of some or all of our assets, including as part of bankruptcy, liquidation, or similar proceeding.</li>
                            <li>We also will disclose information for any purpose or to any organization that you authorize or permit, such as when we request your consent to share information and you agree.</li>
                        </ul>
                        <h5>Your Choices</h5>
                        <h6>We respect your privacy and offer choices regarding our collection and use of your personal information.</h6>
                        <ul>
                            <li>You may choose not to provide the personal information we request. However, not providing information we request may restrict your ability to use certain features of the Website. For example, we will not be able to provide you with most of our services, such as calculating your carbon footprint, if you do not provide the information we request.</li>
                            <li>You may opt out of receiving interested-based ads served by us or on our behalf. For more information about interest-based advertising, including whether you may be able to opt out of this type of advertising by third parties that participate in self-regulatory programs, please visit the Network Advertising Initiative (NAI) and/or the digital Advertising Alliance (DAA) Self-Regulatory Program for Online Behavioral Advertising. Opting out does not mean you will no longer receive advertising. It means that the company or companies from which you opted out will no longer deliver ads tailored to your web preferences and usage patterns.</li>
                            <li>You may be able to restrict the collection of personal information or functionality through your device's operating system or by disabling cookies but doing so may prevent you from using the functionality of the Website. Some Internet browsers have a “do-not-track” feature that let you tell websites that you do not want to have your online activities tracked. At this time the Website does not respond to browser “do not track” signals. We may allow third parties to use the Website to collect personal information about your online activities over time and across different websites, applications, and other online products or services.</li>
                        </ul>
                        <h5>Security</h5>
                        <h6>We maintain safeguards intended to protect the personal information collected through the Website. The security of your personal information also depends on you. You should make sure your devices and software are up-to-date to ensure the latest security measures are installed. </h6>
                        <h5>Changes to this Policy</h5>
                        <h6>We may update this Policy to reflect changes in our privacy practices at any time and without prior notice to you. When we do so, we will update the Effective Date of the Policy, above. We encourage you to periodically review this Policy for the latest information on our privacy practices.</h6>
                        <h5>Contacting Us</h5>
                        <h6>If you have any questions or comments about this Policy or our privacy practices, please contact us at: <a href="mailto:hello@greenplacestowork.com">hello@greenplacestowork.com</a>.</h6>
                    </div>
                </div>
            </div>
        </section>
    </div>
@endsection

@push('scripts')

 
@endpush